import type { NeonExtension } from "./types";

export const NEON_EXTENSIONS: NeonExtension[] = [
  { name: "address_standardizer", status: "available", pg16: "3.3.3", pg17: "3.5.0" },
  { name: "address_standardizer_data_us", status: "available", pg16: "3.3.3", pg17: "3.5.0" },
  { name: "adminpack", status: "not_supported", comments: "Admin operations not supported on managed Postgres" },
  { name: "amcheck", status: "not_supported", comments: "Not listed as supported on Neon" },
  { name: "anon", status: "available", pg16: "2.5.1", pg17: "2.5.1", comments: "Anonymization & data masking; library must be enabled" },
  { name: "Apache AGE", status: "not_supported", comments: "Graph workloads: use pgvector or external graph DB" },
  { name: "autoinc", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "bloom", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "btree_gin", status: "available", pg16: "1.3", pg17: "1.3" },
  { name: "btree_gist", status: "available", pg16: "1.7", pg17: "1.7" },
  { name: "citext", status: "available", pg16: "1.6", pg17: "1.6" },
  { name: "cube", status: "available", pg16: "1.5", pg17: "1.5" },
  { name: "dblink", status: "available", pg16: "1.2", pg17: "1.2" },
  { name: "dict_int", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "earthdistance", status: "available", pg16: "1.2", pg17: "1.2", comments: "Requires cube extension" },
  { name: "fuzzystrmatch", status: "available", pg16: "1.2", pg17: "1.2" },
  { name: "h3", status: "available", pg16: "4.1.3", pg17: "4.1.3", comments: "Install with h3_postgis for spatial integration" },
  { name: "h3_postgis", status: "available", pg16: "4.1.3", pg17: "4.1.3", comments: "Requires postgis and postgis_raster" },
  { name: "hll", status: "available", pg16: "2.19", pg17: "2.19" },
  { name: "hstore", status: "available", pg16: "1.8", pg17: "1.8" },
  { name: "hypopg", status: "available", pg16: "1.4.2", pg17: "1.4.2" },
  { name: "insert_username", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "intagg", status: "available", pg16: "1.1", pg17: "1.1" },
  { name: "intarray", status: "available", pg16: "1.5", pg17: "1.5" },
  { name: "ip4r", status: "available", pg16: "2.4", pg17: "2.4" },
  { name: "isn", status: "available", pg16: "1.2", pg17: "1.2" },
  { name: "lo", status: "available", pg16: "1.1", pg17: "1.1" },
  { name: "ltree", status: "available", pg16: "1.2", pg17: "1.3" },
  { name: "moddatetime", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "neon", status: "available", pg16: "1.14", pg17: "1.14", comments: "Neon system extension; preloaded by default" },
  { name: "neon_utils", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "online_advisor", status: "available", pg17: "1.0", comments: "Only available on Postgres 17" },
  { name: "pageinspect", status: "not_supported", comments: "Not listed as supported on Neon" },
  { name: "pg_buffercache", status: "not_supported", comments: "Not listed as supported on Neon" },
  { name: "pg_cron", status: "available", pg16: "1.6", pg17: "1.6", comments: "Jobs only run when compute is active; disable scale-to-zero for reliability" },
  { name: "pg_freespacemap", status: "not_supported", comments: "Not listed as supported on Neon" },
  { name: "pg_graphql", status: "available", pg16: "1.5.11", pg17: "1.5.11" },
  { name: "pg_hashids", status: "available", pg16: "1.2.1", pg17: "1.2.1" },
  { name: "pg_hint_plan", status: "available", pg16: "1.6.0", pg17: "1.7.0" },
  { name: "pg_ivm", status: "available", pg16: "1.9", pg17: "1.9" },
  { name: "pg_jsonschema", status: "available", pg16: "0.3.3", pg17: "0.3.3" },
  { name: "pg_mooncake", status: "under_review", pg16: "0.1.3", pg17: "0.1.3", comments: "Experimental; requires neon.allow_unstable_extensions=true" },
  { name: "pg_partman", status: "available", pg16: "5.1.0", pg17: "5.1.0", comments: "Background worker pg_partman_bgw preloaded by default" },
  { name: "pg_prewarm", status: "available", pg16: "1.2", pg17: "1.2" },
  { name: "pg_repack", status: "under_review", pg16: "1.5.2", pg17: "1.5.2", comments: "Paid plans only; must be enabled via Neon Support ticket" },
  { name: "pg_roaringbitmap", status: "available", pg16: "0.5", pg17: "0.5", comments: "Install with CREATE EXTENSION roaringbitmap" },
  { name: "pg_search", status: "under_review", pg16: "0.15.26", pg17: "0.15.26", comments: "Deprecated; not available for new projects, existing installs must migrate before June 1, 2026" },
  { name: "pg_session_jwt", status: "available", pg16: "0.4.0", pg17: "0.4.0", comments: "JWT session management used by Neon Data API" },
  { name: "pg_stat_statements", status: "available", pg16: "1.10", pg17: "1.11", comments: "Query performance insights; preloaded by default" },
  { name: "pg_tiktoken", status: "available", pg16: "0.0.1", pg17: "0.0.1" },
  { name: "pg_trgm", status: "available", pg16: "1.6", pg17: "1.6" },
  { name: "pg_uuidv7", status: "available", pg16: "1.6", pg17: "1.6" },
  { name: "pg_visibility", status: "not_supported", comments: "Not listed as supported on Neon" },
  { name: "pgaudit", status: "not_supported", comments: "Not listed as supported on Neon" },
  { name: "pgcrypto", status: "available", pg16: "1.3", pg17: "1.3" },
  { name: "pgjwt", status: "available", pg16: "0.2.0", pg17: "0.2.0" },
  { name: "pglogical", status: "not_supported", comments: "Use Neon logical replication instead" },
  { name: "pgrag", status: "under_review", pg16: "0.0.0", pg17: "0.0.0", comments: "Experimental; requires neon.allow_unstable_extensions=true" },
  { name: "pgrouting", status: "available", pg16: "3.4.2", pg17: "3.6.2", comments: "PostGIS must be installed first" },
  { name: "pgrowlocks", status: "available", pg16: "1.2", pg17: "1.2" },
  { name: "pgstattuple", status: "available", pg16: "1.5", pg17: "1.5" },
  { name: "pgtap", status: "available", pg16: "1.3.3", pg17: "1.3.3" },
  { name: "pgx_ulid", status: "available", pg16: "0.1.5", pg17: "0.2.0", comments: "Install with CREATE EXTENSION ulid on PG16, pgx_ulid on PG17" },
  { name: "plcoffee", status: "available", pg16: "3.1.10", comments: "Not available on PG17" },
  { name: "plls", status: "available", pg16: "3.1.10", comments: "Not available on PG17" },
  { name: "plpgsql", status: "available", pg16: "1.0", pg17: "1.0", comments: "Pre-installed with Postgres" },
  { name: "plpgsql_check", status: "available", pg16: "2.8.2", pg17: "2.8.2" },
  { name: "plv8", status: "not_supported", pg16: "3.1.10", pg17: "3.2.3", comments: "Deprecated; new installs are blocked for security reasons" },
  { name: "postgis", status: "available", pg16: "3.3.3", pg17: "3.5.0", comments: "Full PostGIS support" },
  { name: "postgis_raster", status: "available", pg16: "3.3.3", pg17: "3.5.0" },
  { name: "postgis_sfcgal", status: "available", pg16: "3.3.3", pg17: "3.5.0" },
  { name: "postgis_tiger_geocoder", status: "available", pg16: "3.3.3", pg17: "3.5.0", comments: "Cannot be installed via Neon SQL Editor; use psql" },
  { name: "postgis_topology", status: "available", pg16: "3.3.3", pg17: "3.5.0" },
  { name: "postgres_fdw", status: "available", pg16: "1.1", pg17: "1.1" },
  { name: "prefix", status: "available", pg16: "1.2.0", pg17: "1.2.0" },
  { name: "rdkit", status: "available", pg16: "4.3.0", pg17: "4.6.0" },
  { name: "refint", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "rum", status: "available", pg16: "1.3", pg17: "1.3" },
  { name: "seg", status: "available", pg16: "1.4", pg17: "1.4" },
  { name: "semver", status: "available", pg16: "0.32.1", pg17: "0.40.0" },
  { name: "tablefunc", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "tcn", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "timescaledb", status: "available", pg16: "2.13.0", pg17: "2.17.1", comments: "Apache-2 licensed features only; compression not supported" },
  { name: "tsm_system_rows", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "tsm_system_time", status: "available", pg16: "1.0", pg17: "1.0" },
  { name: "unaccent", status: "available", pg16: "1.1", pg17: "1.1" },
  { name: "unit", status: "available", pg16: "7", pg17: "7" },
  { name: "uuid-ossp", status: "available", pg16: "1.1", pg17: "1.1", comments: 'Double-quote the extension name when installing: CREATE EXTENSION "uuid-ossp"' },
  { name: "vector", status: "available", pg16: "0.8.0", pg17: "0.8.0", comments: "pgvector for AI/ML workloads; install with CREATE EXTENSION vector" },
  { name: "wal2json", status: "available", pg16: "2.6", pg17: "2.6", comments: "CREATE EXTENSION not required; requires logical replication enabled" },
  { name: "xml2", status: "available", pg16: "1.1", pg17: "1.1" },
];

export function getExtensionStatus(name: string): NeonExtension | undefined {
  return NEON_EXTENSIONS.find(
    (e) => e.name.toLowerCase() === name.toLowerCase(),
  );
}

export function countByStatus(status: NeonExtension["status"]): number {
  return NEON_EXTENSIONS.filter((e) => e.status === status).length;
}
