import type { NeonExtension } from "./types";

// Version availability and descriptions synced from the PostgreSQL Extensions
// Manager reference dataset on 2026-08-14. Neon-specific policy notes are
// retained separately in `comments`.
export const EXTENSION_PG_MAJORS = ["14", "15", "16", "17", "18"] as const;

export const NEON_EXTENSIONS: NeonExtension[] = [
  {
    name: "address_standardizer",
    status: "available",
    pg14: "3.3.3",
    pg15: "3.3.3",
    pg16: "3.3.3",
    pg17: "3.5.0",
    pg18: "3.6.0",
    description:
      "Used to parse an address into constituent elements. Generally used to support geocoding address normalization step.",
  },
  {
    name: "address_standardizer_data_us",
    status: "available",
    pg14: "3.3.3",
    pg15: "3.3.3",
    pg16: "3.3.3",
    pg17: "3.5.0",
    pg18: "3.6.0",
    description: "Address Standardizer US dataset example",
  },
  {
    name: "adminpack",
    status: "not_supported",
    pg14: "2.1",
    pg15: "2.1",
    pg16: "2.1",
    description: "administrative functions for PostgreSQL",
    comments: "Admin operations not supported on managed Postgres",
  },
  {
    name: "amcheck",
    status: "not_supported",
    pg14: "1.3",
    pg15: "1.3",
    pg16: "1.3",
    pg17: "1.4",
    pg18: "1.5",
    description: "functions for verifying relation integrity",
    comments: "Not listed as supported on Neon",
  },
  {
    name: "anon",
    status: "available",
    pg14: "2.5.1",
    pg15: "2.5.1",
    pg16: "2.5.1",
    pg17: "2.5.1",
    pg18: "2.5.1",
    description: "Anonymization & Data Masking for PostgreSQL",
    comments: "Anonymization & data masking; library must be enabled",
  },
  {
    name: "Apache AGE",
    status: "not_supported",
    comments: "Graph workloads: use pgvector or external graph DB",
  },
  {
    name: "autoinc",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "functions for autoincrementing fields",
  },
  {
    name: "bloom",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "bloom access method - signature file based index",
  },
  {
    name: "btree_gin",
    status: "available",
    pg14: "1.3",
    pg15: "1.3",
    pg16: "1.3",
    pg17: "1.3",
    pg18: "1.3",
    description: "support for indexing common datatypes in GIN",
  },
  {
    name: "btree_gist",
    status: "available",
    pg14: "1.6",
    pg15: "1.7",
    pg16: "1.7",
    pg17: "1.7",
    pg18: "1.8",
    description: "support for indexing common datatypes in GiST",
  },
  {
    name: "citext",
    status: "available",
    pg14: "1.6",
    pg15: "1.6",
    pg16: "1.6",
    pg17: "1.6",
    pg18: "1.8",
    description: "data type for case-insensitive character strings",
  },
  {
    name: "cube",
    status: "available",
    pg14: "1.5",
    pg15: "1.5",
    pg16: "1.5",
    pg17: "1.5",
    pg18: "1.5",
    description: "data type for multidimensional cubes",
  },
  {
    name: "dblink",
    status: "available",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.2",
    description: "connect to other PostgreSQL databases from within a database",
  },
  {
    name: "dict_int",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "text search dictionary template for integers",
  },
  {
    name: "dict_xsyn",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description:
      "text search dictionary template for extended synonym processing",
  },
  {
    name: "earthdistance",
    status: "available",
    pg14: "1.1",
    pg15: "1.1",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.2",
    description: "calculate great-circle distances on the surface of the Earth",
    comments: "Requires cube extension",
  },
  {
    name: "file_fdw",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "foreign-data wrapper for flat file access",
  },
  {
    name: "fuzzystrmatch",
    status: "available",
    pg14: "1.1",
    pg15: "1.1",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.2",
    description: "determine similarities and distance between strings",
  },
  {
    name: "h3",
    status: "available",
    pg14: "4.1.3",
    pg15: "4.1.3",
    pg16: "4.1.3",
    pg17: "4.1.3",
    pg18: "4.2.3",
    description: "H3 bindings for PostgreSQL",
    comments: "Install with h3_postgis for spatial integration",
  },
  {
    name: "h3_postgis",
    status: "available",
    pg14: "4.1.3",
    pg15: "4.1.3",
    pg16: "4.1.3",
    pg17: "4.1.3",
    pg18: "4.2.3",
    description: "H3 PostGIS integration",
    comments: "Requires postgis and postgis_raster",
  },
  {
    name: "hll",
    status: "available",
    pg14: "2.21",
    pg15: "2.21",
    pg16: "2.21",
    pg17: "2.21",
    pg18: "2.21",
    description: "type for storing hyperloglog data",
  },
  {
    name: "hstore",
    status: "available",
    pg14: "1.8",
    pg15: "1.8",
    pg16: "1.8",
    pg17: "1.8",
    pg18: "1.8",
    description: "data type for storing sets of (key, value) pairs",
  },
  {
    name: "hypopg",
    status: "available",
    pg14: "1.4.3",
    pg15: "1.4.3",
    pg16: "1.4.3",
    pg17: "1.4.3",
    pg18: "1.4.3",
    description: "Hypothetical indexes for PostgreSQL",
  },
  {
    name: "insert_username",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "functions for tracking who changed a table",
  },
  {
    name: "intagg",
    status: "available",
    pg14: "1.1",
    pg15: "1.1",
    pg16: "1.1",
    pg17: "1.1",
    pg18: "1.1",
    description: "integer aggregator and enumerator (obsolete)",
  },
  {
    name: "intarray",
    status: "available",
    pg14: "1.5",
    pg15: "1.5",
    pg16: "1.5",
    pg17: "1.5",
    pg18: "1.5",
    description:
      "functions, operators, and index support for 1-D arrays of integers",
  },
  {
    name: "ip4r",
    status: "available",
    pg14: "2.4",
    pg15: "2.4",
    pg16: "2.4",
    pg17: "2.4",
    pg18: "2.4",
    description:
      "data types and operators for storing, indexing, and manipulating IPv4 and IPv6 addresses and ranges",
  },
  {
    name: "isn",
    status: "available",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.3",
    description: "data types for international product numbering standards",
  },
  {
    name: "lakebase_text",
    status: "available",
    pg16: "0.1.0-dev",
    pg17: "0.1.0-dev",
    pg18: "0.1.0-dev",
    description: "lakebase_text",
  },
  {
    name: "lakebase_tokenizer",
    status: "available",
    pg16: "0.1.0",
    pg17: "0.1.0",
    pg18: "0.1.0",
    description: "lakebase_tokenizer: full text search tokenizer",
  },
  {
    name: "lakebase_vector",
    status: "available",
    pg16: "1.0.0-dev",
    pg17: "1.0.0-dev",
    pg18: "1.0.0-dev",
    description: "lakebase_vector",
  },
  {
    name: "lo",
    status: "available",
    pg14: "1.1",
    pg15: "1.1",
    pg16: "1.1",
    pg17: "1.1",
    pg18: "1.2",
    description: "Large Object maintenance",
  },
  {
    name: "ltree",
    status: "available",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.3",
    pg18: "1.3",
    description: "data type for hierarchical tree-like structures",
  },
  {
    name: "moddatetime",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "functions for tracking last modification time",
  },
  {
    name: "neon",
    status: "available",
    pg14: "1.14",
    pg15: "1.14",
    pg16: "1.14",
    pg17: "1.14",
    pg18: "1.14",
    description: "cloud storage for PostgreSQL",
    comments: "Neon system extension; preloaded by default",
  },
  {
    name: "neon_monitor",
    status: "available",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description:
      "Neon database monitoring: execution plan capture, ASH, wait events",
  },
  {
    name: "neon_rmgr",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description:
      "Neon WAL Resource Manager - custom WAL records used to make Neon work (since PG 16)",
  },
  {
    name: "neon_utils",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "neon_utils - small useful functions",
  },
  {
    name: "old_snapshot",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    description: "utilities in support of old_snapshot_threshold",
  },
  {
    name: "online_advisor",
    status: "available",
    pg17: "1.0",
    description: "Online index advisor",
    comments: "Only available on Postgres 17",
  },
  {
    name: "pageinspect",
    status: "not_supported",
    pg14: "1.9",
    pg15: "1.11",
    pg16: "1.12",
    pg17: "1.12",
    pg18: "1.13",
    description: "inspect the contents of database pages at a low level",
    comments: "Not listed as supported on Neon",
  },
  {
    name: "pg_buffercache",
    status: "not_supported",
    pg14: "1.3",
    pg15: "1.3",
    pg16: "1.4",
    pg17: "1.5",
    pg18: "1.6",
    description: "examine the shared buffer cache",
    comments: "Not listed as supported on Neon",
  },
  {
    name: "pg_cron",
    status: "available",
    pg14: "1.6",
    pg15: "1.6",
    pg16: "1.6",
    pg17: "1.6",
    pg18: "1.6",
    description: "Job scheduler for PostgreSQL",
    comments:
      "Jobs only run when compute is active; disable scale-to-zero for reliability",
  },
  {
    name: "pg_duckdb",
    status: "available",
    pg14: "0.3.0",
    pg15: "0.3.0",
    pg16: "0.3.0",
    pg17: "0.3.0",
    description: "DuckDB Embedded in Postgres",
  },
  {
    name: "pg_freespacemap",
    status: "not_supported",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.3",
    description: "examine the free space map (FSM)",
    comments: "Not listed as supported on Neon",
  },
  {
    name: "pg_graphql",
    status: "available",
    pg14: "1.5.11",
    pg15: "1.5.11",
    pg16: "1.5.11",
    pg17: "1.5.11",
    pg18: "1.5.12",
    description: "pg_graphql: GraphQL support",
  },
  {
    name: "pg_hashids",
    status: "available",
    pg14: "1.2.1",
    pg15: "1.2.1",
    pg16: "1.2.1",
    pg17: "1.2.1",
    pg18: "1.2.1",
    description: "pg_hashids",
  },
  {
    name: "pg_hint_plan",
    status: "available",
    pg14: "1.4.1",
    pg15: "1.5",
    pg16: "1.6.0",
    pg17: "1.7.0",
    pg18: "1.8.0",
    description: "optimizer hints for PostgreSQL",
  },
  { name: "pg_ivm", status: "available", pg16: "1.9", pg17: "1.9" },
  {
    name: "pg_jsonschema",
    status: "available",
    pg14: "0.3.3",
    pg15: "0.3.3",
    pg16: "0.3.3",
    pg17: "0.3.3",
    pg18: "0.3.4",
    description: "pg_jsonschema",
  },
  {
    name: "pg_logicalinspect",
    status: "available",
    pg18: "1.0",
    description: "functions to inspect logical decoding components",
  },
  {
    name: "pg_mooncake",
    status: "under_review",
    pg14: "0.1.3",
    pg15: "0.1.3",
    pg16: "0.1.3",
    pg17: "0.1.3",
    description: "Columnstore Table in Postgres",
    comments: "Experimental; requires neon.allow_unstable_extensions=true",
  },
  {
    name: "pg_partman",
    status: "available",
    pg14: "5.1.0",
    pg15: "5.1.0",
    pg16: "5.1.0",
    pg17: "5.1.0",
    pg18: "5.1.0",
    description: "Extension to manage partitioned tables by time or ID",
    comments: "Background worker pg_partman_bgw preloaded by default",
  },
  {
    name: "pg_prewarm",
    status: "available",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.2",
    description: "prewarm relation data",
  },
  {
    name: "pg_repack",
    status: "under_review",
    pg14: "1.5.2",
    pg15: "1.5.2",
    pg16: "1.5.2",
    pg17: "1.5.2",
    pg18: "1.5.2",
    description: "Reorganize tables in PostgreSQL databases with minimal locks",
    comments: "Paid plans only; must be enabled via Neon Support ticket",
  },
  {
    name: "pg_roaringbitmap",
    status: "available",
    pg16: "0.5",
    pg17: "0.5",
    comments: "Install with CREATE EXTENSION roaringbitmap",
  },
  {
    name: "pg_search",
    status: "under_review",
    pg14: "0.15.26",
    pg15: "0.15.26",
    pg16: "0.15.26",
    pg17: "0.15.26",
    pg18: "0.15.26",
    description: "pg_search: Full text search for PostgreSQL using BM25",
    comments:
      "Deprecated; not available for new projects, existing installs must migrate before June 1, 2026",
  },
  {
    name: "pg_session_jwt",
    status: "available",
    pg14: "0.5.0",
    pg15: "0.5.0",
    pg16: "0.5.0",
    pg17: "0.5.0",
    pg18: "0.5.0",
    description: "pg_session_jwt: manage authentication sessions using JWTs",
    comments: "JWT session management used by Neon Data API",
  },
  {
    name: "pg_stat_statements",
    status: "available",
    pg14: "1.9",
    pg15: "1.10",
    pg16: "1.10",
    pg17: "1.11",
    pg18: "1.12",
    description:
      "track planning and execution statistics of all SQL statements executed",
    comments: "Query performance insights; preloaded by default",
  },
  {
    name: "pg_surgery",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "extension to perform surgery on a damaged relation",
  },
  {
    name: "pg_tiktoken",
    status: "available",
    pg14: "0.0.1",
    pg15: "0.0.1",
    pg16: "0.0.1",
    pg17: "0.0.1",
    pg18: "0.0.1",
    description:
      "pg_tictoken: tiktoken tokenizer for use with OpenAI models in postgres",
  },
  {
    name: "pg_trgm",
    status: "available",
    pg14: "1.6",
    pg15: "1.6",
    pg16: "1.6",
    pg17: "1.6",
    pg18: "1.6",
    description:
      "text similarity measurement and index searching based on trigrams",
  },
  {
    name: "pg_uuidv7",
    status: "available",
    pg14: "1.6",
    pg15: "1.6",
    pg16: "1.6",
    pg17: "1.6",
    pg18: "1.6",
    description: "pg_uuidv7: create UUIDv7 values in postgres",
  },
  {
    name: "pg_visibility",
    status: "not_supported",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.2",
    description:
      "examine the visibility map (VM) and page-level visibility info",
    comments: "Not listed as supported on Neon",
  },
  {
    name: "pg_walinspect",
    status: "available",
    pg15: "1.0",
    pg16: "1.1",
    pg17: "1.1",
    pg18: "1.1",
    description: "functions to inspect contents of PostgreSQL Write-Ahead Log",
  },
  {
    name: "pgaudit",
    status: "not_supported",
    pg14: "1.6.3",
    pg15: "1.7.1",
    pg16: "16.1",
    pg17: "17.1",
    pg18: "18.0",
    description: "provides auditing functionality",
    comments: "Not listed as supported on Neon",
  },
  {
    name: "pgauditlogtofile",
    status: "available",
    pg14: "1.6",
    pg15: "1.6",
    pg16: "1.6",
    pg17: "1.6",
    pg18: "1.7",
    description:
      "pgAudit addon to redirect audit entries to an independent file",
  },
  {
    name: "pgcrypto",
    status: "available",
    pg14: "1.3",
    pg15: "1.3",
    pg16: "1.3",
    pg17: "1.3",
    pg18: "1.4",
    description: "cryptographic functions",
  },
  {
    name: "pgjwt",
    status: "available",
    pg14: "0.2.0",
    pg15: "0.2.0",
    pg16: "0.2.0",
    pg17: "0.2.0",
    pg18: "0.2.0",
    description: "JSON Web Token API for Postgresql",
  },
  {
    name: "pglogical",
    status: "not_supported",
    comments: "Use Neon logical replication instead",
  },
  {
    name: "pgrag",
    status: "under_review",
    pg16: "0.0.0",
    pg17: "0.0.0",
    comments: "Experimental; requires neon.allow_unstable_extensions=true",
  },
  {
    name: "pgrouting",
    status: "available",
    pg14: "3.4.2",
    pg15: "3.4.2",
    pg16: "3.4.2",
    pg17: "3.6.2",
    pg18: "3.8.0",
    description: "pgRouting Extension",
    comments: "PostGIS must be installed first",
  },
  {
    name: "pgrowlocks",
    status: "available",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.2",
    description: "show row-level locking information",
  },
  {
    name: "pgstattuple",
    status: "available",
    pg14: "1.5",
    pg15: "1.5",
    pg16: "1.5",
    pg17: "1.5",
    pg18: "1.5",
    description: "show tuple-level statistics",
  },
  {
    name: "pgtap",
    status: "available",
    pg14: "1.3.3",
    pg15: "1.3.3",
    pg16: "1.3.3",
    pg17: "1.3.3",
    pg18: "1.3.3",
    description: "Unit testing for PostgreSQL",
  },
  {
    name: "pgx_ulid",
    status: "available",
    pg17: "0.2.0",
    pg18: "0.2.2",
    description: "ulid type and methods",
    comments: "Install with CREATE EXTENSION ulid on PG16, pgx_ulid on PG17",
  },
  {
    name: "plcoffee",
    status: "available",
    pg14: "3.1.10",
    pg15: "3.1.10",
    pg16: "3.1.10",
    description: "PL/CoffeeScript (v8) trusted procedural language",
    comments: "Not available on PG17",
  },
  {
    name: "plls",
    status: "available",
    pg14: "3.1.10",
    pg15: "3.1.10",
    pg16: "3.1.10",
    description: "PL/LiveScript (v8) trusted procedural language",
    comments: "Not available on PG17",
  },
  {
    name: "plpgsql",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "PL/pgSQL procedural language",
    comments: "Pre-installed with Postgres",
  },
  {
    name: "plpgsql_check",
    status: "available",
    pg14: "2.8",
    pg15: "2.8",
    pg16: "2.8",
    pg17: "2.8",
    pg18: "2.8",
    description: "extended check for plpgsql functions",
  },
  {
    name: "plv8",
    status: "not_supported",
    pg14: "3.1.10",
    pg15: "3.1.10",
    pg16: "3.1.10",
    pg17: "3.2.3",
    description: "PL/JavaScript (v8) trusted procedural language",
    comments: "Deprecated; new installs are blocked for security reasons",
  },
  {
    name: "postgis",
    status: "available",
    pg14: "3.3.3",
    pg15: "3.3.3",
    pg16: "3.3.3",
    pg17: "3.5.0",
    pg18: "3.6.0",
    description: "PostGIS geometry and geography spatial types and functions",
    comments: "Full PostGIS support",
  },
  {
    name: "postgis_raster",
    status: "available",
    pg14: "3.3.3",
    pg15: "3.3.3",
    pg16: "3.3.3",
    pg17: "3.5.0",
    pg18: "3.6.0",
    description: "PostGIS raster types and functions",
  },
  {
    name: "postgis_sfcgal",
    status: "available",
    pg14: "3.3.3",
    pg15: "3.3.3",
    pg16: "3.3.3",
    pg17: "3.5.0",
    pg18: "3.6.0",
    description: "PostGIS SFCGAL functions",
  },
  {
    name: "postgis_tiger_geocoder",
    status: "available",
    pg14: "3.3.3",
    pg15: "3.3.3",
    pg16: "3.3.3",
    pg17: "3.5.0",
    pg18: "3.6.0",
    description: "PostGIS tiger geocoder and reverse geocoder",
    comments: "Cannot be installed via Neon SQL Editor; use psql",
  },
  {
    name: "postgis_topology",
    status: "available",
    pg14: "3.3.3",
    pg15: "3.3.3",
    pg16: "3.3.3",
    pg17: "3.5.0",
    pg18: "3.6.0",
    description: "PostGIS topology spatial types and functions",
  },
  {
    name: "postgres_fdw",
    status: "available",
    pg14: "1.1",
    pg15: "1.1",
    pg16: "1.1",
    pg17: "1.1",
    pg18: "1.2",
    description: "foreign-data wrapper for remote PostgreSQL servers",
  },
  {
    name: "prefix",
    status: "available",
    pg14: "1.2.0",
    pg15: "1.2.0",
    pg16: "1.2.0",
    pg17: "1.2.0",
    pg18: "1.2.0",
    description: "Prefix Range module for PostgreSQL",
  },
  {
    name: "rag",
    status: "available",
    pg14: "0.0.0",
    pg15: "0.0.0",
    pg16: "0.0.0",
    pg17: "0.0.0",
    pg18: "0.0.0",
    description:
      "Tools to support Retrieval-Augmented Generation: https://github.com/neondatabase-labs/pgrag",
  },
  {
    name: "rag_bge_small_en_v15",
    status: "available",
    pg14: "0.0.0",
    pg15: "0.0.0",
    pg16: "0.0.0",
    pg17: "0.0.0",
    pg18: "0.0.0",
    description:
      "In-database embeddings generation using model bge-small-en-v1.5: https://github.com/neondatabase-labs/pgrag",
  },
  {
    name: "rag_jina_reranker_v1_tiny_en",
    status: "available",
    pg14: "0.0.0",
    pg15: "0.0.0",
    pg16: "0.0.0",
    pg17: "0.0.0",
    pg18: "0.0.0",
    description:
      "In-database reranking using model jina-reranker-v1-tiny-en: https://github.com/neondatabase-labs/pgrag",
  },
  {
    name: "rdkit",
    status: "available",
    pg14: "4.3.0",
    pg15: "4.3.0",
    pg16: "4.3.0",
    pg17: "4.6.0",
    pg18: "4.8.0",
    description: "Cheminformatics functionality for PostgreSQL.",
  },
  {
    name: "refint",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "functions for implementing referential integrity (obsolete)",
  },
  {
    name: "roaringbitmap",
    status: "available",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.2",
    description: "support for Roaring Bitmaps",
  },
  {
    name: "rum",
    status: "available",
    pg14: "1.3",
    pg15: "1.3",
    pg16: "1.3",
    pg17: "1.3",
    description: "RUM index access method",
  },
  {
    name: "seg",
    status: "available",
    pg14: "1.4",
    pg15: "1.4",
    pg16: "1.4",
    pg17: "1.4",
    pg18: "1.4",
    description:
      "data type for representing line segments or floating-point intervals",
  },
  {
    name: "semver",
    status: "available",
    pg14: "0.32.1",
    pg15: "0.32.1",
    pg16: "0.32.1",
    pg17: "0.40.0",
    pg18: "0.40.0",
    description: "Semantic version data type",
  },
  {
    name: "sslinfo",
    status: "available",
    pg14: "1.2",
    pg15: "1.2",
    pg16: "1.2",
    pg17: "1.2",
    pg18: "1.2",
    description: "information about SSL certificates",
  },
  {
    name: "tablefunc",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "functions that manipulate whole tables, including crosstab",
  },
  {
    name: "tcn",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "Triggered change notifications",
  },
  {
    name: "timescaledb",
    status: "available",
    pg14: "2.10.1",
    pg15: "2.10.1",
    pg16: "2.13.0",
    pg17: "2.17.1",
    pg18: "2.24.0",
    description:
      "Enables scalable inserts and complex queries for time-series data",
    comments: "Apache-2 licensed features only; compression not supported",
  },
  {
    name: "tsm_system_rows",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description: "TABLESAMPLE method which accepts number of rows as a limit",
  },
  {
    name: "tsm_system_time",
    status: "available",
    pg14: "1.0",
    pg15: "1.0",
    pg16: "1.0",
    pg17: "1.0",
    pg18: "1.0",
    description:
      "TABLESAMPLE method which accepts time in milliseconds as a limit",
  },
  {
    name: "ulid",
    status: "available",
    pg14: "0.1.5",
    pg15: "0.1.5",
    pg16: "0.1.5",
    description: "ulid type and methods",
  },
  {
    name: "unaccent",
    status: "available",
    pg14: "1.1",
    pg15: "1.1",
    pg16: "1.1",
    pg17: "1.1",
    pg18: "1.1",
    description: "text search dictionary that removes accents",
  },
  {
    name: "unit",
    status: "available",
    pg14: "7",
    pg15: "7",
    pg16: "7",
    pg17: "7",
    description: "SI units extension",
  },
  {
    name: "uuid-ossp",
    status: "available",
    pg14: "1.1",
    pg15: "1.1",
    pg16: "1.1",
    pg17: "1.1",
    pg18: "1.1",
    description: "generate universally unique identifiers (UUIDs)",
    comments:
      'Double-quote the extension name when installing: CREATE EXTENSION "uuid-ossp"',
  },
  {
    name: "vector",
    status: "available",
    pg14: "0.8.0",
    pg15: "0.8.0",
    pg16: "0.8.0",
    pg17: "0.8.0",
    pg18: "0.8.6",
    description: "vector data type and ivfflat and hnsw access methods",
    comments:
      "pgvector for AI/ML workloads; install with CREATE EXTENSION vector",
  },
  {
    name: "wal2json",
    status: "available",
    pg16: "2.6",
    pg17: "2.6",
    comments:
      "CREATE EXTENSION not required; requires logical replication enabled",
  },
  {
    name: "xml2",
    status: "available",
    pg14: "1.1",
    pg15: "1.1",
    pg16: "1.1",
    pg17: "1.1",
    pg18: "1.2",
    description: "XPath querying and XSLT",
  },
];

export function getExtensionStatus(name: string): NeonExtension | undefined {
  return NEON_EXTENSIONS.find(
    (extension) => extension.name.toLowerCase() === name.toLowerCase(),
  );
}

export function countByStatus(status: NeonExtension["status"]): number {
  return NEON_EXTENSIONS.filter((extension) => extension.status === status)
    .length;
}
